// Generated from urdf_inspect_standard_en.md and urdf_inspect_stantard_zh.md by scripts/generate_inspection_criteria.mjs.
// Do not edit this file directly.

export const GENERATED_INSPECTION_CRITERIA = [
  {
    "id": "spec",
    "name": "URDF Spec Compliance",
    "nameZh": "URDF 规范合规",
    "weight": 0.2,
    "items": [
      {
        "id": "robot_root_contract",
        "name": "Robot Root Contract",
        "nameZh": "机器人根节点契约",
        "description": "The document must have a single `<robot>` root with a stable `name`. Top-level children should be compatible with the intended consumer: core URDF (`link`, `joint`, `material`) plus clearly documented extensions (`transmission`, `gazebo`, `sensor`, custom tags).",
        "descriptionZh": "文档必须具有唯一的 `<robot>` 根节点，并带有稳定的 `name`。 顶层子元素应与目标消费方兼容：核心 URDF（`link`、`joint`、`material`）以及被明确说明的扩展（`transmission`、`gazebo`、`sensor`、自定义标签）。",
        "scoringReference": "Missing/invalid root scores 0 points; undocumented extension mixing scores 4-6 points.",
        "scoringReferenceZh": "根节点缺失/非法计 0 分；未说明的扩展混用计 4-6 分。",
        "maxScore": 10
      },
      {
        "id": "link_joint_required_fields",
        "name": "Link / Joint Required Fields",
        "nameZh": "Link / Joint 必填字段",
        "description": "Every `link` must have a unique `name`. Every `joint` must have `name`, `type`, `<parent link=\"...\">`, and `<child link=\"...\">`. Parent/child references must point to existing links.",
        "descriptionZh": "每个 `link` 都必须有唯一 `name`。 每个 `joint` 都必须有 `name`、`type`、`<parent link=\"...\">` 与 `<child link=\"...\">`。 parent/child 引用必须指向真实存在的 link。",
        "scoringReference": "Missing required fields or broken references score 0-3 points.",
        "scoringReferenceZh": "必填字段缺失或引用断裂计 0-3 分。",
        "maxScore": 10
      },
      {
        "id": "topology_tree_constraint",
        "name": "Tree Topology Constraint",
        "nameZh": "树拓扑约束",
        "description": "Core URDF models are trees, not general graphs. There should be exactly one logical root, no orphan links, and no closed loops unless a downstream tool adds extra constraints outside core URDF semantics.",
        "descriptionZh": "核心 URDF 模型是树，不是一般图结构。 应当只有一个逻辑根节点，不允许存在孤立 link，也不应直接在核心 URDF 语义中编码闭环，除非闭环由下游工具在 URDF 之外额外表达。",
        "scoringReference": "Multiple roots, disconnected subgraphs, or closed-loop encoding in plain URDF score 0-2 points.",
        "scoringReferenceZh": "多根、断裂子图或直接用普通 URDF 编码闭环计 0-2 分。",
        "maxScore": 10
      },
      {
        "id": "joint_semantics",
        "name": "Joint Semantic Rules",
        "nameZh": "关节语义规则",
        "description": "Axis, limits, mimic, calibration, and safety-related tags must match the joint type semantics. `continuous` joints should not rely on position bounds. `mimic` targets must exist and the relationship should be intentional/documented.",
        "descriptionZh": "axis、limit、mimic、calibration 与安全相关标签必须符合对应关节类型的语义。 `continuous` 关节不应依赖位置上下界。 `mimic` 的目标关节必须存在，且关系应是明确、有意图的。",
        "scoringReference": "Type-incompatible tags or contradictory joint semantics score 2-5 points.",
        "scoringReferenceZh": "与类型冲突的标签或自相矛盾的关节语义计 2-5 分。",
        "maxScore": 10
      },
      {
        "id": "extension_compatibility",
        "name": "Extension Compatibility",
        "nameZh": "扩展兼容性",
        "description": "`transmission`, `gazebo`, `sensor`, and custom tags are extension surfaces, not universally supported core URDF. Review whether the file documents its intended consumers and whether unsupported extensions are safely ignorable or required for correctness.",
        "descriptionZh": "`transmission`、`gazebo`、`sensor` 以及自定义标签属于扩展面，不是所有消费方都支持的核心 URDF。 需要审查文件是否说明了目标消费方，以及这些扩展在不支持的环境中是可忽略的，还是实际上依赖它们才能正确工作。",
        "scoringReference": "Hidden consumer-specific dependencies or undocumented required extensions score 3-6 points.",
        "scoringReferenceZh": "存在隐藏的消费方依赖，或必须扩展却没有说明，计 3-6 分。",
        "maxScore": 10
      }
    ]
  },
  {
    "id": "physical",
    "name": "Physical Plausibility",
    "nameZh": "物理合理性",
    "weight": 0.2,
    "items": [
      {
        "id": "mass_inertia_basic",
        "name": "Mass & Inertia Validity",
        "nameZh": "质量与惯性有效性",
        "description": "All Link masses must be $>0$. All diagonal elements of the inertia matrix $(ixx, iyy, izz)$ must be $>0$. Must satisfy triangle inequality: $ixx + iyy > izz, ixx + izz > iyy, iyy + izz > ixx$.",
        "descriptionZh": "所有 Link 质量必须 $>0$。 惯性矩阵对角线元素 $(ixx, iyy, izz)$ 必须全部 $>0$。 必须满足三角不等式：$ixx + iyy > izz, ixx + izz > iyy, iyy + izz > ixx$。",
        "scoringReference": "0 or negative values score 0 points; inequality violations score 2-4 points.",
        "scoringReferenceZh": "存在 0 或负值计 0 分；不满足不等式计 2-4 分。",
        "maxScore": 10
      },
      {
        "id": "inertia_overlap",
        "name": "Inertia-Visual Match",
        "nameZh": "惯性分布与体积匹配",
        "description": "In simulators (e.g., MuJoCo), the inertia block size should roughly match the Link's own volume. The inertia block position should highly overlap with the geometry, and its orientation should reflect the principal axes of mass distribution.",
        "descriptionZh": "在仿真器（如 MuJoCo）中，惯性块的大小应与 Link 本身的体积大致相当。 惯性块位置应与几何形状高度重叠，姿态反映质量分布主轴。",
        "scoringReference": "Severe offset or extremely disproportionate size of inertia block scores 4 points.",
        "scoringReferenceZh": "惯性块严重偏移或大小极其不成比例计 4 分。",
        "maxScore": 10
      },
      {
        "id": "symmetry_check",
        "name": "Symmetry Consistency",
        "nameZh": "左右对称一致性",
        "description": "Symmetric Links on both sides of the body should maintain strict symmetry in mass, inertia tensor, and center of mass position (error $<1\\%$). The orientation of the inertia coordinate system should also satisfy mirror symmetry.",
        "descriptionZh": "身体两侧对称 Link 的质量、惯性张量、质心位置应保持严格对称（误差 $<1\\%$）。 惯性坐标系的姿态也需满足镜像对称。",
        "scoringReference": "Obvious deviation in parameters between both sides scores 6 points.",
        "scoringReferenceZh": "两侧参数偏差明显计 6 分。",
        "maxScore": 10
      }
    ]
  },
  {
    "id": "frames",
    "name": "Link Frames",
    "nameZh": "坐标系位置与朝向",
    "weight": 0.15,
    "items": [
      {
        "id": "frame_alignment",
        "name": "Joint Collinearity",
        "nameZh": "关节原点共线关系",
        "description": "When the robot is in standard standing posture, the joint origins of the limbs should form collinear relationships. Sagittal plane: Joint connections should form a nearly vertical line from top to bottom. Coronal plane: Origin connections of both legs/arms should form four mutually parallel vertical lines. Adjustment method: Achieved by moving the coordinate system from the flange to the motor rotation axis center.",
        "descriptionZh": "机器人处于标准站立姿态时，四肢关节原点应构成共线关系。 矢状面：关节连线接近一条从上到下的贯穿线。 冠状面：双腿/双臂原点连线应构成四条相互平行的垂直线。 调整手段：通过将坐标系从法兰盘移至电机转轴中心来实现。",
        "scoringReference": "Chaotic origin distribution or failure to consider motor axis alignment scores 5 points.",
        "scoringReferenceZh": "原点分布杂乱、未考虑电机转轴对齐计 5 分。",
        "maxScore": 10
      },
      {
        "id": "axis_convention",
        "name": "Axis Convention",
        "nameZh": "坐标系朝向公约",
        "description": "Unified convention: Z-axis upward, Y-axis leftward, X-axis forward. Special joints (e.g., oblique hip pitch): Z-axis perpendicular to the flange plane, Y-axis follows right-hand rule, X-axis maintains forward direction. Joints whose rotation plane is not parallel to the ground (e.g., some hip yaw): Still must enforce X forward, Z upward.",
        "descriptionZh": "统一公约：Z轴向上，Y轴向左，X轴向前。 特殊关节（如斜向 hip pitch）：Z轴垂直于法兰平面，Y轴符合右手定则，X轴保持向前。 旋转面与地面不平行的关节（如部分 hip yaw）：仍需强制 X 朝前，Z 朝上。",
        "scoringReference": "Inconsistent axes score 3 points.",
        "scoringReferenceZh": "轴向不统一计 3 分。",
        "maxScore": 10
      },
      {
        "id": "waist_check",
        "name": "Waist Centering & Equal Length Alignment",
        "nameZh": "腰部中心与等长对齐",
        "description": "The waist joint must be located at the geometric center, ensuring that the distances from the left and right limbs to the waist origin are completely equal in length.",
        "descriptionZh": "腰部关节 (waist) 必须位于几何中心，确保左右侧肢体到腰部原点的距离完全等长。",
        "scoringReference": "Offset or asymmetric center scores 5 points.",
        "scoringReferenceZh": "偏置或非对称中心计 5 分。",
        "maxScore": 10
      }
    ]
  },
  {
    "id": "assembly",
    "name": "Assembly Logic",
    "nameZh": "装配逻辑合理性",
    "weight": 0.1,
    "items": [
      {
        "id": "motor_placement",
        "name": "Actuator Mass Attribution",
        "nameZh": "驱动器质量归属",
        "description": "If the drive motor is physically installed inside the parent Link, its mass and inertia must be included in the parent Link. Example: The mass of a linear motor inside the thigh should be included in the thigh Link.",
        "descriptionZh": "若驱动电机物理安装在上级 Link 内部，其质量和惯性必须计入上级 Link。 例如：大腿内部的位移电机质量应计入大腿 Link。",
        "scoringReference": "Incorrect motor attribution to Link scores 4 points.",
        "scoringReferenceZh": "电机归属 Link 错误计 4 分。",
        "maxScore": 10
      },
      {
        "id": "linkage_placement",
        "name": "Linkage Attribution",
        "nameZh": "传动与连杆归属",
        "description": "Drive linkages and transmission components should be assigned to the child Link they actually drive. Foot drive linkages belong to the Foot Link, not the shank.",
        "descriptionZh": "驱动连杆及传动件应划归到其实际驱动的子级 Link 中。 脚部驱动连杆归属于 Foot Link，而非小腿。",
        "scoringReference": "Confused mass allocation of transmission components scores 6 points.",
        "scoringReferenceZh": "传动件质量分配混乱计 6 分。",
        "maxScore": 10
      }
    ]
  },
  {
    "id": "simulation",
    "name": "Kinematics & Simulation Properties",
    "nameZh": "运动学与仿真属性",
    "weight": 0.15,
    "items": [
      {
        "id": "tree_connectivity",
        "name": "Topology Validation",
        "nameZh": "树状结构验证",
        "description": "Must have a single root node (e.g., base_link), no closed loops or isolated Links allowed.",
        "descriptionZh": "必须单一根节点（如 base_link），不允许存在闭环或孤立 Link。",
        "scoringReference": "Logical structure errors score 0 points.",
        "scoringReferenceZh": "逻辑结构错误计 0 分。",
        "maxScore": 10
      },
      {
        "id": "joint_limits",
        "name": "Joint Limits Reasonableness",
        "nameZh": "关节限位合理性",
        "description": "lower < upper; limit values must match motor specifications and mechanical hard limits.",
        "descriptionZh": "lower < upper；限位值需与电机规格及机械硬限位匹配。",
        "scoringReference": "Reversed limits score 0 points; undefined limits score 5 points.",
        "scoringReferenceZh": "限位反向计 0 分；未定义限位计 5 分。",
        "maxScore": 10
      },
      {
        "id": "collision_simplify",
        "name": "Collision Body Optimization",
        "nameZh": "碰撞体优化",
        "description": "Collision models must be simplified (using Box/Cylinder, etc.), prohibiting direct copying of high-precision Visual Mesh.",
        "descriptionZh": "碰撞模型必须简化（使用 Box/Cylinder 等），禁止直接复制高精度 Visual Mesh。",
        "scoringReference": "Not simplified scores 5 points.",
        "scoringReferenceZh": "未简化计 5 分。",
        "maxScore": 10
      }
    ]
  },
  {
    "id": "hardware",
    "name": "Hardware Parameter Configuration",
    "nameZh": "硬件参数配置",
    "weight": 0.1,
    "items": [
      {
        "id": "motor_limits",
        "name": "Motor Torque & Velocity Limits",
        "nameZh": "电机力矩与速度限位",
        "description": "Effort and velocity limit values must conform to the rated/peak parameters of the selected motor.",
        "descriptionZh": "effort 和 velocity 限位值需符合选型电机的额定/峰值参数。",
        "scoringReference": "Missing parameters score 6 points.",
        "scoringReferenceZh": "参数缺失计 6 分。",
        "maxScore": 10
      },
      {
        "id": "armature_config",
        "name": "Armature/Rotor Inertia",
        "nameZh": "电枢/转子惯量",
        "description": "Whether armature values reflecting the motor rotor and reduction ratio equivalent inertia are configured (especially important for low-mass, high-reduction-ratio robots).",
        "descriptionZh": "是否配置了反映电机转子和减速比等效惯量的 armature 值（特别是对小质量高减速比机器人）。",
        "scoringReference": "Missing configuration scores 7 points.",
        "scoringReferenceZh": "缺失计 7 分。",
        "maxScore": 10
      }
    ]
  },
  {
    "id": "naming",
    "name": "Naming Conventions",
    "nameZh": "命名规范",
    "weight": 0.1,
    "items": [
      {
        "id": "naming_standard",
        "name": "Uniqueness & Descriptiveness",
        "nameZh": "唯一性与描述性",
        "description": "Names must be globally unique and semantic (e.g., L_hip_pitch_link). Follow snake_case style.",
        "descriptionZh": "名称全局唯一，具有语义化（如 L_hip_pitch_link）。 遵循 snake_case 风格。",
        "scoringReference": "Duplicate names score 0 points; inconsistent style scores 8 points.",
        "scoringReferenceZh": "重名计 0 分；风格不统一计 8 分。",
        "maxScore": 10
      }
    ]
  }
];
