export const PROPERTY_EDITOR_POSITION_STEP = 0.001;
export const PROPERTY_EDITOR_STEPPER_REPEAT_DELAY_MS = 300;
export const PROPERTY_EDITOR_STEPPER_REPEAT_INTERVAL_MS = 60;
export const PROPERTY_EDITOR_TRANSFORM_STEPPER_REPEAT_INTERVAL_MS = 16;
