import fs from 'node:fs';
import path from 'node:path';

const repoRoot = process.cwd();
const sourcePath = path.join(repoRoot, 'src/features/ai-assistant/config/aiPromptTemplates.md');
const outputPath = path.join(
  repoRoot,
  'src/features/ai-assistant/config/aiPromptTemplates.generated.ts',
);

const source = fs.readFileSync(sourcePath, 'utf8');

const REQUIRED_PROMPT_SECTIONS = ['generation', 'inspection.en', 'inspection.zh'];
const REQUIRED_SECTION_PLACEHOLDERS = {
  generation: ['__ROBOT_CONTEXT__', '__MOTOR_LIBRARY_CONTEXT__'],
  'inspection.en': ['__CRITERIA_DESCRIPTION__', '__INSPECTION_NOTES__', '__LANGUAGE_INSTRUCTION__'],
  'inspection.zh': ['__CRITERIA_DESCRIPTION__', '__INSPECTION_NOTES__', '__LANGUAGE_INSTRUCTION__'],
};

const sectionPattern = /<!-- PROMPT: ([^\n]+?) -->\n([\s\S]*?)\n<!-- \/PROMPT -->/g;
const promptSections = new Map();

for (const match of source.matchAll(sectionPattern)) {
  const [, id, content] = match;
  const trimmedId = id.trim();
  if (promptSections.has(trimmedId)) {
    throw new Error(`Duplicate prompt section "${trimmedId}" found in ${sourcePath}`);
  }

  promptSections.set(trimmedId, content.trim());
}

for (const requiredId of REQUIRED_PROMPT_SECTIONS) {
  if (!promptSections.has(requiredId)) {
    throw new Error(`Prompt section "${requiredId}" not found in ${sourcePath}`);
  }
}

const extractPrompt = (id) => {
  const prompt = promptSections.get(id);
  if (!prompt) {
    throw new Error(`Prompt section "${id}" not found in ${sourcePath}`);
  }

  for (const placeholder of REQUIRED_SECTION_PLACEHOLDERS[id] || []) {
    if (!prompt.includes(placeholder)) {
      throw new Error(`Prompt section "${id}" is missing required placeholder ${placeholder}`);
    }
  }

  return prompt;
};

const generatedModule = `// Generated from aiPromptTemplates.md by scripts/generate_ai_prompt_templates.mjs.
// Do not edit this file directly.

export const AI_PROMPT_TEMPLATES = {
  generation: ${JSON.stringify(extractPrompt('generation'))},
  inspection: {
    en: ${JSON.stringify(extractPrompt('inspection.en'))},
    zh: ${JSON.stringify(extractPrompt('inspection.zh'))}
  }
} as const;
`;

fs.writeFileSync(outputPath, generatedModule);
